#!/usr/bin/env bun
/**
 * Generates an icon mapping file for the docs app.
 * Maps block/trigger types to their icon React components.
 *
 * Output: apps/docs/components/ui/icon-mapping.ts
 *
 * This allows BlockInfoCard to import and render actual React icon components
 * instead of extracting SVG strings — handles all icon types correctly including
 * raster-embedded SVGs like CirclebackIcon.
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const rootDir = path.resolve(__dirname, '..', '..')

const BLOCKS_DIR = path.join(rootDir, 'apps/tradinggoose/blocks/blocks')
const ICONS_DIR = path.join(rootDir, 'apps/tradinggoose/components/icons')
const OUTPUT_FILE = path.join(rootDir, 'apps/docs/components/ui/icon-mapping.ts')
const ICONS_OUTPUT = path.join(rootDir, 'apps/docs/components/icons.tsx')

// 1. Scan all icon files to build a set of available icon names
const availableIcons = new Set<string>()
const iconFiles = ['icons.tsx', 'provider-icons.tsx', 'util-icons.tsx']

for (const file of iconFiles) {
  const filePath = path.join(ICONS_DIR, file)
  if (!fs.existsSync(filePath)) continue
  const content = fs.readFileSync(filePath, 'utf-8')

  const fnRegex = /export\s+(?:function|const)\s+(\w+Icon)/g
  let m
  while ((m = fnRegex.exec(content)) !== null) {
    availableIcons.add(m[1])
  }
}

console.log(`Found ${availableIcons.size} icon components`)

// 2. Scan all block files to build type → iconName mapping
const typeToIcon = new Map<string, string>()

const blockFiles = fs.readdirSync(BLOCKS_DIR).filter(f => f.endsWith('.ts') && !f.endsWith('.test.ts'))
for (const file of blockFiles) {
  const content = fs.readFileSync(path.join(BLOCKS_DIR, file), 'utf-8')

  const typeMatch = content.match(/type\s*:\s*['"]([^'"]+)['"]/)
  const iconMatch = content.match(/icon\s*:\s*(\w+Icon)/)

  if (typeMatch && iconMatch && availableIcons.has(iconMatch[1])) {
    typeToIcon.set(typeMatch[1], iconMatch[1])
  }
}

// 3. Register custom icons (lucide-style) that will be appended to the icons file
availableIcons.add('ChatTriggerIcon')
availableIcons.add('ManualTriggerIcon')
availableIcons.add('InputTriggerIcon')

// 4. Add trigger-specific mappings
const triggerIconMap: Record<string, string> = {
  api_trigger: 'ApiIcon',
  chat_trigger: 'ChatTriggerIcon',
  manual_trigger: 'ManualTriggerIcon',
  input_trigger: 'InputTriggerIcon',
  schedule: 'ScheduleIcon',
  generic_webhook: 'WebhookIcon',
}
for (const [type, icon] of Object.entries(triggerIconMap)) {
  if (availableIcons.has(icon)) {
    typeToIcon.set(type, icon)
  }
}

console.log(`Mapped ${typeToIcon.size} block types to icons`)

// 4. Group icons by source file for organized imports
const iconToSourceFile = new Map<string, string>()
for (const file of iconFiles) {
  const filePath = path.join(ICONS_DIR, file)
  if (!fs.existsSync(filePath)) continue
  const content = fs.readFileSync(filePath, 'utf-8')

  const fnRegex = /export\s+(?:function|const)\s+(\w+Icon)/g
  let m
  while ((m = fnRegex.exec(content)) !== null) {
    iconToSourceFile.set(m[1], file)
  }
}

// 5. Copy all icon source files into a single docs-side icons.tsx
let iconsContent = `// Auto-generated file - do not edit manually\n// Generated by scripts/doc-gen/generate-icon-mapping.ts\n\nimport type { SVGProps } from 'react'\n\n`

for (const file of iconFiles) {
  const filePath = path.join(ICONS_DIR, file)
  if (!fs.existsSync(filePath)) continue
  let content = fs.readFileSync(filePath, 'utf-8')
  // Remove the import of SVGProps (we add it once at top)
  content = content.replace(/import\s+type?\s*\{[^}]*SVGProps[^}]*\}\s*from\s*['"]react['"]\s*;?\n?/g, '')
  // Remove any other imports that won't resolve in docs context
  content = content.replace(/import\s+.*from\s+['"]@\/.*['"]\s*;?\n?/g, '')
  // Remove helper functions that reference app-specific code
  content = content.replace(/function withThemeAwareColorClass[\s\S]*?\n\}/g, '')
  iconsContent += `// --- From ${file} ---\n${content}\n\n`
}

// Append custom icons for types that use lucide icons (not available as SVG exports)
// These use consistent lucide-style: 24x24 viewBox, strokeWidth=2, round linecap/linejoin
iconsContent += `
// --- Custom trigger icons (lucide-style) ---
export function ChatTriggerIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg {...props} viewBox='0 0 24 24' fill='none' xmlns='http://www.w3.org/2000/svg' stroke='currentColor' strokeWidth='2' strokeLinecap='round' strokeLinejoin='round'>
      <path d='M7.9 20A9 9 0 1 0 4 16.1L2 22Z'/>
    </svg>
  )
}

export function ManualTriggerIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg {...props} viewBox='0 0 24 24' fill='none' xmlns='http://www.w3.org/2000/svg' stroke='currentColor' strokeWidth='2' strokeLinecap='round' strokeLinejoin='round'>
      <polygon points='6 3 20 12 6 21 6 3'/>
    </svg>
  )
}

export function InputTriggerIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg {...props} viewBox='0 0 24 24' fill='none' xmlns='http://www.w3.org/2000/svg' stroke='currentColor' strokeWidth='2' strokeLinecap='round' strokeLinejoin='round'>
      <rect width='18' height='18' x='3' y='3' rx='2'/>
      <path d='M7 7h10'/>
      <path d='M7 12h10'/>
      <path d='M7 17h6'/>
    </svg>
  )
}
`
fs.writeFileSync(ICONS_OUTPUT, iconsContent)
console.log(`Generated ${ICONS_OUTPUT} (${Math.round(iconsContent.length / 1024)}KB)`)

// 6. Generate the icon mapping file
const usedIcons = new Set<string>(typeToIcon.values())
const sortedUsedIcons = [...usedIcons].sort()

let output = `// Auto-generated file - do not edit manually
// Generated by scripts/doc-gen/generate-icon-mapping.ts
// Maps block types to their icon component references

import type { ComponentType, SVGProps } from 'react'
import {\n  ${sortedUsedIcons.join(',\n  ')},\n} from '@/components/icons'
`

output += `
type IconComponent = ComponentType<SVGProps<SVGSVGElement> & { className?: string }>

export const blockTypeToIconMap: Record<string, IconComponent> = {\n`

const entries = [...typeToIcon.entries()].sort((a, b) => a[0].localeCompare(b[0]))
for (const [type, icon] of entries) {
  output += `  '${type}': ${icon},\n`
}

output += `}\n`

fs.writeFileSync(OUTPUT_FILE, output)
console.log(`Generated ${OUTPUT_FILE}`)
