export const CHAT_ERROR_CODES = {
  AUTH_REQUIRED_PASSWORD: 'auth_required_password',
  AUTH_REQUIRED_EMAIL: 'auth_required_email',
  AUTH_REQUIRED_SSO: 'auth_required_sso',
  PASSWORD_REQUIRED: 'password_required',
  INVALID_PASSWORD: 'invalid_password',
  AUTH_CONFIGURATION_ERROR: 'authentication_configuration_error',
  AUTHENTICATION_ERROR: 'authentication_error',
  EMAIL_REQUIRED: 'email_required',
  INVALID_EMAIL: 'invalid_email',
  EMAIL_NOT_AUTHORIZED: 'email_not_authorized',
  OTP_REQUIRED: 'otp_required',
  OTP_NOT_FOUND: 'otp_not_found',
  OTP_INVALID: 'otp_invalid',
  OTP_SEND_FAILED: 'otp_send_failed',
  OTP_RESEND_FAILED: 'otp_resend_failed',
  OTP_VERIFY_FAILED: 'otp_verify_failed',
  SSO_EMAIL_NOT_AUTHORIZED: 'sso_email_not_authorized',
  SSO_AUTHENTICATION_REQUIRED: 'sso_authentication_required',
  SSO_SESSION_MISSING_EMAIL: 'sso_session_missing_email',
  SSO_AUTHENTICATION_ERROR: 'sso_authentication_error',
  UNSUPPORTED_AUTHENTICATION_TYPE: 'unsupported_authentication_type',
  CHAT_NOT_FOUND: 'chat_not_found',
  CHAT_UNAVAILABLE: 'chat_unavailable',
  NO_CHAT_TRIGGER: 'no_chat_trigger',
  USAGE_LIMIT_EXCEEDED: 'usage_limit_exceeded',
  FAILED_TO_LOAD_CONFIG: 'failed_to_load_config',
  FAILED_TO_GET_RESPONSE: 'failed_to_get_response',
  RESPONSE_BODY_MISSING: 'response_body_missing',
  FAILED_TO_SEND_MESSAGE: 'failed_to_send_message',
  REQUEST_TIMED_OUT: 'request_timed_out',
  GENERIC_ERROR: 'generic_error',
  RESPONSE_STOPPED_BY_USER: 'response_stopped_by_user',
  INVALID_REQUEST_BODY: 'invalid_request_body',
  NO_INPUT_PROVIDED: 'no_input_provided',
  CHAT_WORKFLOW_NOT_AVAILABLE: 'chat_workflow_not_available',
  API_KEY_REQUIRED: 'api_key_required',
  PENDING_EXECUTION_BACKLOG_FULL: 'pending_execution_backlog_full',
  FAILED_TO_PROCESS_REQUEST: 'failed_to_process_request',
  FAILED_TO_FETCH_CHAT_INFORMATION: 'failed_to_fetch_chat_information',
  INVALID_REQUEST: 'invalid_request',
  CHAT_AUTH_TYPE_NOT_EMAIL: 'chat_auth_type_not_email',
  VERIFICATION_CODE_MISSING: 'verification_code_missing',
  VERIFICATION_CODE_SEND_FAILED: 'verification_code_send_failed',
  VERIFICATION_CODE_RESEND_FAILED: 'verification_code_resend_failed',
  VERIFICATION_CODE_INVALID: 'verification_code_invalid',
  VERIFICATION_CODE_VERIFY_FAILED: 'verification_code_verify_failed',
  SYSTEM_SETTINGS_UNAUTHORIZED: 'unauthorized',
  SYSTEM_SETTINGS_FORBIDDEN: 'forbidden',
  SYSTEM_SETTINGS_INVALID_REQUEST: 'invalid_request_data',
  SYSTEM_SETTINGS_LOAD_FAILED: 'failed_to_load_system_settings',
  SYSTEM_SETTINGS_UPDATE_FAILED: 'failed_to_update_system_settings',
  SYSTEM_SETTINGS_BILLING_NOT_CONFIGURED: 'billing_not_configured',
  SYSTEM_SETTINGS_BILLING_NOT_READY: 'billing_not_ready',
  SYSTEM_SETTINGS_TRIGGER_NOT_READY: 'trigger_not_ready',
} as const

export const CHAT_REQUEST_TIMEOUT_MS = 300000 // 5 minutes (same as in chat.tsx)

export type ChatErrorCode = (typeof CHAT_ERROR_CODES)[keyof typeof CHAT_ERROR_CODES]
