import { Clock } from 'lucide-react'
import { fetchTimeZoneOptions } from '@/components/timezone-selector/fetchers'
import type { TriggerConfig } from '@/triggers/types'

export const scheduleTrigger: TriggerConfig = {
  id: 'schedule',
  name: 'Schedule',
  webhookProvider: 'schedule',
  description: 'Trigger workflow execution on a schedule',
  version: '1.0.0',
  icon: Clock,
  subBlocks: [
    {
      id: 'scheduleType',
      type: 'dropdown',
      title: 'Run frequency',
      options: [
        { label: 'Every X Minutes', id: 'minutes' },
        { label: 'Hourly', id: 'hourly' },
        { label: 'Daily', id: 'daily' },
        { label: 'Weekly', id: 'weekly' },
        { label: 'Monthly', id: 'monthly' },
        { label: 'Custom Cron', id: 'custom' },
      ],
      value: () => 'daily',
      required: true,
      mode: 'trigger',
    },
    {
      id: 'minutesInterval',
      type: 'short-input',
      inputType: 'number',
      title: 'Interval (minutes)',
      placeholder: '15',
      required: true,
      mode: 'trigger',
      condition: { field: 'scheduleType', value: 'minutes' },
    },
    {
      id: 'hourlyMinute',
      type: 'short-input',
      inputType: 'number',
      title: 'Minute',
      placeholder: '0-59',
      required: true,
      mode: 'trigger',
      condition: { field: 'scheduleType', value: 'hourly' },
    },
    {
      id: 'dailyTime',
      type: 'time-input',
      title: 'Time',
      required: true,
      mode: 'trigger',
      condition: { field: 'scheduleType', value: 'daily' },
    },
    {
      id: 'weeklyDay',
      type: 'dropdown',
      title: 'Day of week',
      options: [
        { label: 'Monday', id: 'MON' },
        { label: 'Tuesday', id: 'TUE' },
        { label: 'Wednesday', id: 'WED' },
        { label: 'Thursday', id: 'THU' },
        { label: 'Friday', id: 'FRI' },
        { label: 'Saturday', id: 'SAT' },
        { label: 'Sunday', id: 'SUN' },
      ],
      required: true,
      mode: 'trigger',
      condition: { field: 'scheduleType', value: 'weekly' },
    },
    {
      id: 'weeklyDayTime',
      type: 'time-input',
      title: 'Time',
      required: true,
      mode: 'trigger',
      condition: { field: 'scheduleType', value: 'weekly' },
    },
    {
      id: 'monthlyDay',
      type: 'short-input',
      inputType: 'number',
      title: 'Day of month',
      placeholder: '1-31',
      required: true,
      mode: 'trigger',
      condition: { field: 'scheduleType', value: 'monthly' },
    },
    {
      id: 'monthlyTime',
      type: 'time-input',
      title: 'Time',
      required: true,
      mode: 'trigger',
      condition: { field: 'scheduleType', value: 'monthly' },
    },
    {
      id: 'cronExpression',
      type: 'short-input',
      title: 'Cron expression',
      placeholder: '0 0 * * *',
      required: true,
      mode: 'trigger',
      condition: { field: 'scheduleType', value: 'custom' },
    },
    {
      id: 'timezone',
      type: 'dropdown',
      title: 'Timezone',
      enableSearch: true,
      fetchOptions: fetchTimeZoneOptions,
      value: () => 'UTC',
      required: false,
      mode: 'trigger',
      condition: { field: 'scheduleType', value: ['minutes', 'hourly'], not: true },
    },
    {
      id: 'scheduleConfig',
      title: 'Schedule Status',
      type: 'schedule-config',
      layout: 'full',
      mode: 'trigger',
      hideFromPreview: true,
    },
  ],
  outputs: {},
}
