import type { ComponentType, SVGProps } from 'react'
import { createElement } from 'react'
import { Activity, PauseCircle, Repeat } from 'lucide-react'
import * as icons from '@/components/icons'

type IconComponent = ComponentType<SVGProps<SVGSVGElement> & { className?: string }>

const IndicatorTriggerIcon: IconComponent = (props) => createElement(Activity, props)
const LoopIcon: IconComponent = (props) => createElement(Repeat, props)
const WaitIcon: IconComponent = (props) => createElement(PauseCircle, props)

const baseTypeToIconMap: Record<string, IconComponent> = {
  agent: icons.AgentIcon,
  ahrefs: icons.AhrefsIcon,
  airtable: icons.AirtableIcon,
  api: icons.ApiIcon,
  api_trigger: icons.ApiIcon,
  apify: icons.ApifyIcon,
  apollo: icons.ApolloIcon,
  arxiv: icons.ArxivIcon,
  asana: icons.AsanaIcon,
  browser_use: icons.BrowserUseIcon,
  calendly: icons.CalendlyIcon,
  chat_trigger: icons.ChatTriggerIcon,
  circleback: icons.CirclebackIcon,
  clay: icons.ClayIcon,
  condition: icons.ConditionalIcon,
  confluence: icons.ConfluenceIcon,
  cursor: icons.CursorIcon,
  datadog: icons.DatadogIcon,
  discord: icons.DiscordIcon,
  dropbox: icons.DropboxIcon,
  duckduckgo: icons.DuckDuckGoIcon,
  dynamodb: icons.DynamoDBIcon,
  elasticsearch: icons.ElasticsearchIcon,
  elevenlabs: icons.ElevenLabsIcon,
  exa: icons.ExaAIIcon,
  file: icons.DocumentIcon,
  firecrawl: icons.FirecrawlIcon,
  fireflies: icons.FirefliesIcon,
  function: icons.CodeIcon,
  generic_webhook: icons.WebhookIcon,
  github: icons.GithubIcon,
  gitlab: icons.GitLabIcon,
  gmail: icons.GmailIcon,
  google_calendar: icons.GoogleCalendarIcon,
  google_docs: icons.GoogleDocsIcon,
  google_drive: icons.GoogleDriveIcon,
  google_forms: icons.GoogleFormsIcon,
  google_groups: icons.GoogleGroupsIcon,
  google_search: icons.GoogleIcon,
  google_sheets: icons.GoogleSheetsIcon,
  google_slides: icons.GoogleSlidesIcon,
  google_vault: icons.GoogleVaultIcon,
  grafana: icons.GrafanaIcon,
  grain: icons.GrainIcon,
  greptile: icons.GreptileIcon,
  guardrails: icons.ShieldCheckIcon,
  historical_data: icons.ChartBarIcon,
  hubspot: icons.HubspotIcon,
  huggingface: icons.HuggingFaceIcon,
  human_in_the_loop: icons.HumanInTheLoopIcon,
  hunter: icons.HunterIOIcon,
  image_generator: icons.ImageIcon,
  incidentio: icons.IncidentioIcon,
  input_trigger: icons.InputTriggerIcon,
  intercom: icons.IntercomIcon,
  jina: icons.JinaAIIcon,
  jira: icons.JiraIcon,
  jira_service_management: icons.JiraServiceManagementIcon,
  kalshi: icons.KalshiIcon,
  knowledge: icons.PackageSearchIcon,
  linear: icons.LinearIcon,
  linkedin: icons.LinkedInIcon,
  linkup: icons.LinkupIcon,
  loop: LoopIcon,
  mailchimp: icons.MailchimpIcon,
  mailgun: icons.MailgunIcon,
  manual_trigger: icons.ManualTriggerIcon,
  mcp: icons.ServerIcon,
  mem0: icons.Mem0Icon,
  memory: icons.BrainIcon,
  microsoft_excel: icons.MicrosoftExcelIcon,
  microsoft_planner: icons.MicrosoftPlannerIcon,
  microsoft_teams: icons.MicrosoftTeamsIcon,
  mistral_parse: icons.MistralIcon,
  mongodb: icons.MongoDBIcon,
  mysql: icons.MySQLIcon,
  neo4j: icons.Neo4jIcon,
  note: icons.NoteIcon,
  notion: icons.NotionIcon,
  number: icons.ChartBarIcon,
  'oauth-input': icons.DollarIcon,
  onedrive: icons.MicrosoftOneDriveIcon,
  openai: icons.OpenAIIcon,
  outlook: icons.OutlookIcon,
  parallel_ai: icons.ParallelIcon,
  perplexity: icons.PerplexityIcon,
  pinecone: icons.PineconeIcon,
  pipedrive: icons.PipedriveIcon,
  polymarket: icons.PolymarketIcon,
  postgresql: icons.PostgresIcon,
  posthog: icons.PosthogIcon,
  qdrant: icons.QdrantIcon,
  rds: icons.RDSIcon,
  reddit: icons.RedditIcon,
  resend: icons.ResendIcon,
  response: icons.ResponseIcon,
  router: icons.ConnectIcon,
  s3: icons.S3Icon,
  salesforce: icons.SalesforceIcon,
  schedule: icons.ScheduleIcon,
  search: icons.SearchIcon,
  sendgrid: icons.SendgridIcon,
  sentry: icons.SentryIcon,
  serper: icons.SerperIcon,
  servicenow: icons.ServiceNowIcon,
  sftp: icons.SftpIcon,
  sharepoint: icons.MicrosoftSharepointIcon,
  shopify: icons.ShopifyIcon,
  slack: icons.SlackIcon,
  sms: icons.SMSIcon,
  smtp: icons.SmtpIcon,
  spotify: icons.SpotifyIcon,
  sqs: icons.SQSIcon,
  ssh: icons.SshIcon,
  stagehand: icons.StagehandIcon,
  stagehand_agent: icons.StagehandIcon,
  stripe: icons.StripeIcon,
  stt: icons.STTIcon,
  supabase: icons.SupabaseIcon,
  tavily: icons.TavilyIcon,
  telegram: icons.TelegramIcon,
  thinking: icons.BrainIcon,
  trading_order_history: icons.DollarIcon,
  translate: icons.TranslateIcon,
  trello: icons.TrelloIcon,
  tts: icons.TTSIcon,
  twilio_sms: icons.TwilioIcon,
  twilio_voice: icons.TwilioIcon,
  typeform: icons.TypeformIcon,
  video_generator: icons.VideoIcon,
  vision: icons.EyeIcon,
  wealthbox: icons.WealthboxIcon,
  webflow: icons.WebflowIcon,
  webhook_request: icons.WebhookIcon,
  whatsapp: icons.WhatsAppIcon,
  wikipedia: icons.WikipediaIcon,
  wordpress: icons.WordpressIcon,
  workflow: icons.WorkflowIcon,
  workflow_input: icons.WorkflowIcon,
  x: icons.xIcon,
  youtube: icons.YouTubeIcon,
  zendesk: icons.ZendeskIcon,
  zep: icons.ZepIcon,
  zoom: icons.ZoomIcon,
}

const docsTypeToIconMap: Record<string, IconComponent> = {
  airtable_webhook: icons.AirtableIcon,
  calendly_invitee_canceled: icons.CalendlyIcon,
  calendly_invitee_created: icons.CalendlyIcon,
  calendly_routing_form_submitted: icons.CalendlyIcon,
  calendly_webhook: icons.CalendlyIcon,
  circleback_meeting_completed: icons.CirclebackIcon,
  circleback_meeting_notes: icons.CirclebackIcon,
  circleback_webhook: icons.CirclebackIcon,
  evaluator: icons.ChartBarIcon,
  fireflies_transcription_complete: icons.FirefliesIcon,
  generic: icons.WebhookIcon,
  github_issue_closed: icons.GithubIcon,
  github_issue_comment: icons.GithubIcon,
  github_issue_opened: icons.GithubIcon,
  github_pr_closed: icons.GithubIcon,
  github_pr_comment: icons.GithubIcon,
  github_pr_merged: icons.GithubIcon,
  github_pr_opened: icons.GithubIcon,
  github_pr_reviewed: icons.GithubIcon,
  github_push: icons.GithubIcon,
  github_release_published: icons.GithubIcon,
  github_webhook: icons.GithubIcon,
  github_workflow_run: icons.GithubIcon,
  gmail_poller: icons.GmailIcon,
  google_forms_webhook: icons.GoogleFormsIcon,
  grain_highlight_created: icons.GrainIcon,
  grain_highlight_updated: icons.GrainIcon,
  grain_recording_created: icons.GrainIcon,
  grain_recording_updated: icons.GrainIcon,
  grain_story_created: icons.GrainIcon,
  grain_webhook: icons.GrainIcon,
  hubspot_company_created: icons.HubspotIcon,
  hubspot_company_deleted: icons.HubspotIcon,
  hubspot_company_property_changed: icons.HubspotIcon,
  hubspot_contact_created: icons.HubspotIcon,
  hubspot_contact_deleted: icons.HubspotIcon,
  hubspot_contact_privacy_deleted: icons.HubspotIcon,
  hubspot_contact_property_changed: icons.HubspotIcon,
  hubspot_conversation_creation: icons.HubspotIcon,
  hubspot_conversation_deletion: icons.HubspotIcon,
  hubspot_conversation_new_message: icons.HubspotIcon,
  hubspot_conversation_privacy_deletion: icons.HubspotIcon,
  hubspot_conversation_property_changed: icons.HubspotIcon,
  hubspot_deal_created: icons.HubspotIcon,
  hubspot_deal_deleted: icons.HubspotIcon,
  hubspot_deal_property_changed: icons.HubspotIcon,
  hubspot_ticket_created: icons.HubspotIcon,
  hubspot_ticket_deleted: icons.HubspotIcon,
  hubspot_ticket_property_changed: icons.HubspotIcon,
  imap: icons.MailServerIcon,
  imap_poller: icons.MailServerIcon,
  indicator: IndicatorTriggerIcon,
  'microsoft-teams': icons.MicrosoftTeamsIcon,
  microsoftteams_chat_subscription: icons.MicrosoftTeamsIcon,
  microsoftteams_webhook: icons.MicrosoftTeamsIcon,
  outlook_poller: icons.OutlookIcon,
  parallel: icons.ParallelIcon,
  rss: icons.RssIcon,
  rss_poller: icons.RssIcon,
  slack_webhook: icons.SlackIcon,
  stripe_webhook: icons.StripeIcon,
  telegram_webhook: icons.TelegramIcon,
  trading_action: icons.DollarIcon,
  trading_holdings: icons.DollarIcon,
  trading_order_detail: icons.DollarIcon,
  twilio_voice_webhook: icons.TwilioIcon,
  variables: icons.Variable,
  wait: WaitIcon,
  webflow_collection_item_changed: icons.WebflowIcon,
  webflow_collection_item_created: icons.WebflowIcon,
  webflow_collection_item_deleted: icons.WebflowIcon,
  webflow_form_submission: icons.WebflowIcon,
  webhook: icons.WebhookIcon,
  whatsapp_webhook: icons.WhatsAppIcon,
}

export function getBlockTypeIcon(type: string): IconComponent {
  const IconComponent = baseTypeToIconMap[type] ?? docsTypeToIconMap[type]

  if (!IconComponent) {
    if (process.env.NODE_ENV !== 'production') {
      console.warn(`Missing icon mapping for docs type "${type}", using WorkflowIcon fallback`)
    }

    return icons.WorkflowIcon
  }

  return IconComponent
}
